### PR TITLE
BL-2: List review

### PR DESCRIPTION
**Pull request by LierB**

### CODE REVIEW

**Comment by Sulstice** [comment]
@asukaorr Hey Asuka, changes are being implemented to your list by @LierB . She is validating and making sure we conform to a standard. Can you review her PR and also make sure we all agree with the changes implemented.

**Comment by Sulstice** [comment]
As you go through the lists, I wouldn't prioritize canionicalism. I know this sounds stupid but I usually like SMILES I can read. If the canonical version is shit then I try to opt for something else that is more readable. 

I really also don't like lowercase letters in SMILES. I don't think you do either.

**Comment by LierB** [comment]
Yes, I agree with you. But usually I think the canonical SMILES read best. Especially as you point out with the lower case letters!!
Here in this list, I didn't like it too much, that the ions were sometimes written in front but mostly at the end. I wanted to unify that as well.

**Comment by Sulstice** [comment]
Hey @LierB I don't actually know what to do here.  Like if we have comments for what it is great, but it can't live like that per se in the code. 

We would need a 1 to 1 mapping still of relevant stuff so I think perhaps we should put them as a translated list to common names. So a translator from FDA to Common Names. 

What do you think?

The design could look like

```python

class FDAColourTranslator(object):

       def get_mapping(self):
```

I think moving forward this could actually scale efficiently and have Global-Chem act as a translator for jargon.

**Comment by LierB** [comment]
Hey @Sulstice 
I was aware, that it can not stay like this. I just wanted to note it for now, that we can think how we want to include them for later. 
I like the idea with a translator! When I've seen it, I thought we can also do this with other lists, or even more generally. To translate all Common names to IUPAC or the other way around. There are endless possibilities actually....

**Pull request closed without merging**
