### PR TITLE
Update named_reactions_in_organic_synthesis.py

### PR DESCRIPTION
**Pull request by Ruibin-Liu**
reformat the list to pass windows tests.

### CODE REVIEW

**Review by Sulstice — COMMENTED** [review]
They need to be in single quotes like this and lower case

```
'ciamician_dennstedt_rearrangement': '',
```

**Comment by Ruibin-Liu** [comment]
> They need to be in single quotes like this and lower case
> 
> ```
> 'ciamician_dennstedt_rearrangement': '',
> ```

So it has to be a dictionary? I thought a set would work. The reaction names contain people's names, so spaces and upper case letters are necessary. At least one of them contains a quote symbol, so I guess double quotes have to be used.

**Comment by Sulstice** [comment]
I think we need to figure out how to reduce it down to lowercase as well as capture any characters that are not part of the ASCII table. Spacing we can keep And yeah you can do double quotes in replacement for somethings that are used as apostrophes.

**Comment by Sulstice** [comment]
This problem seems harder than it is. Going to push this into main for now and handle it on the main branch. I added a lot of other little nick knacks as well.

**Pull request merged**
